### ISSUE TITLE
Service couldn't start

### ISSUE THREAD

**Issue by zxcvbn97** [jeog/TOSDataBridge#1]
Hi @jeog,

Thanks for the library, it looks very helpful.
One problem I had is that I couldn't start its service. 

Attached is a screenshot of TOSDataBridge on a fresh install of Windows 7 SP1. 

![untitled](https://cloud.githubusercontent.com/assets/9757976/8560543/6cbfe0e0-24de-11e5-89b0-31bcdfd82bb2.png)

Is there any way to debug this error? 

Thanks!

**Comment by jeog** [comment]
sorry for the late response,

It's been a while since I debugged the back-end stuff so it's probably
something simple that isn't jumping out at me but a couple things to try:

1) check your anti-virus, when i tried to run this on another system
norton/symantec quietly deleted one of the core
executables(tos-databridge-engine...exe binary) for 'suspicious'
behavior(it does some system level stuff that the av heuristics detect),
when trying to start up the service.  Check your av logs , make sure none
of the files are being deleted/quarantined, or try to add the specific
binaries to the white-list.

2)The service.cpp file attempts to log messages to the relevant AppData
folder; since its running as 'system' it should be located
C:\Windows\System32\config\systemprofile\AppData\Roaming\tos-databridge\service-log.log
( you can always search for tos-databridge\service-log.log if its not
there)  send any relevant log messages you find

let me know what you find...

-jon

**Comment by jeog** [comment]
FWIW, I stumbled onto this myself when updating the stable version I was using. In a more recent update I introduced a bug in service.cpp::ParseArgs() that allowed an empty string pointer to get passed back and converted into an int for the custom_session arg rather than a default; causing service.cpp::SpawnRestrictedProcess() to fail; causing the service to not respond to the start request.

The bug should be fixed in commit 2594f59 - if for some reason one wants to use the old(buggy) binaries they can pass in an explicit session arg (of 1 in most cases) to the setup script (e.g tosdb-setup.bat x64 1) - but that's not recommended.
