### ISSUE TITLE
how to get a symbol's close price of particular time of day ?

### ISSUE THREAD

**Issue by ywlau** [jeog/TOSDataBridge#10]
Hi, is it possible to get the 10am close price of a symbol (as shown in TOS application) ?

Thanks.

**Comment by ywlau** [comment]
Tried first method, close price might be different from actual, as per your explanations.

About the second method, is there a way to access 1 minute bar, as i'm interested to get both 10:00am and 10:01am close prices. Any ref. to TOS script for accessing the 30 minute bar ?


Thanks.

**Comment by jeog** [comment]
You can use whatever bar sizes TOS offers in the ThinkScript. I believe there is a drop-down box at the top of ThinkScript wizard to set the bar size OR you can pass the aggregation period (AggregationPeriod.MIN) directly to the 'close' function.

The problem w/ finding the difference between the current bar and the open is that ThinkScript won't let you use a historical reference that isn't a constant. You'll need to experiment w/ BarNumber() or SecondsFromTime(), possibly using CompoundValue() that will output different values depending on the current bar#, or using some type of conditional statement to check that the current bar IS the 10:00 bar and then return the price, 0 otherwise.  In the latter case you would then have the tosdb script continually check the returned value != 0 and save it when it's not.

I don't really use ThinkScript that much so I'm not sure the best way to do this. If you come up w/ something feel free to share it. I can always create a ThinkScript/CustomQuote Recipe section so others can take advantage of these techniques.

**Comment by ywlau** [comment]
tried assigning close(period = "1 min") to custom in TOS MarketWatch,
"secondary aggregation period cannot be less than the primary" error returned.

any idea ?

**Comment by jeog** [comment]
I believe that sets the secondary aggregation period (you can use different periods in a script). The primary is set at the top of the ThinkScript editor w/ a button next to the column name. The former can't be smaller than the latter.

It's probably easier to just set the primary and don't pass anything to close

**Comment by ywlau** [comment]
the following works for me:

in MarketWatch,
set custom to "close[1]" and primary aggregation period to 1 min

in my app,
read in 10:00am close price at 10:01am
read in 10:01am close price at 10:02am etc.

thanks again.

**Comment by jeog** [comment]
ok, much simpler
