### ISSUE TITLE
TypeError: 'OHLC' object is not iterable

### ISSUE THREAD

**Issue by hcgaron** [jeog/TOSDataBridge#13]
I'm trying to figure out how to use the intervalize module and having a little trouble making the data work.  I tried `ohlc.TOSDB_OpenHighLowCloseIntervals(block2, 12, poll_sec=1)` to test some data retrieval and could get the data but can't unpack it as a tuple so I'm not sure how to use it.  I'm interested in maybe writing values to a CSV file after formatting them properly, but not sure how to access individual values.

Maybe I don't need to use this class at all though.  How do you schedule periodic fetching of data in your python script?  I'm looking into the schedule module. I'd like to read in ohlc every 1, 5, 15, 60 mins for example.  Any pointers you have would be greatly appreciated.

EDIT:  I was able to get the periodic repetition I wanted using the `schedule` module.  So my only question is how to access the data returned by the "intervalize" module?  Or is it advised just to run .get() on a vanilla data block at periodic intervals and access / manipulate the data that way?

**Comment by jeog** [comment]
Its been a while since I wrote/used the intervalize package but I think you should be able to do something like the following to get 60 seconds intervals. (the following is just a general idea, read the docstrings for specifics.)

 create the objects:
```
block = ohlc.tosdb.TOSDB_ThreadSafeDataBlock(10000)
intrv = ohlc.TOSDB_OpenHighLowCloseIntervals(block, 60)
```

 then use the methods to insert the symbols/fields you want:
```
intrv.add_items(...)
intrv.add_topics(...)
```

then use the methods to pull OHLC objects out:
```
intrv.get(...) #a single OHLC
intrv.stream_snapshot(...) # multiples
intrv.stream_snapshot_between_datetimes(...) # a range 
```

Just keep in mind that the idea is to only provide the data after 'n' seconds so it may not be available at each call. I also think there's an optional callback arg you can pass that will get called when its ready.

**Comment by hcgaron** [comment]
Thanks @jeog for the reply.  I was able to get the behavior I wanted using a scheduling module and using `stream_snapshot_from_marker()` at the appropriate intervals, then processing that data with a custom callback.  So it's certainly not a pressing issue, but as far as I can tell, I could view the data if I called `get` or similar, but I couldn't actually access the data, such as indexing a value to be passed to another function or written to file or added to a matrix, etc...

Maybe it is purely my mistake, just thought I'd ask.  But I figured a workaround that might work instead.  I'll try once again to see if I made a mistake.
