### ISSUE TITLE
Setup: can't find serv file

### ISSUE THREAD

**Issue by shnog** [jeog/TOSDataBridge#18]
I am trying to run the tosdb-setup.bat x64 and it keeps telling me it can't find the tos-databridge-serv-x64.exe yet I see it in there
<img width="718" alt="asdasda" src="https://user-images.githubusercontent.com/43620922/53371023-3a82db80-391d-11e9-80df-bc4c3dc52c94.PNG">

<img width="571" alt="asdasdsadsad" src="https://user-images.githubusercontent.com/43620922/53371033-3f478f80-391d-11e9-8bb5-999c14a0e2e9.PNG">

**Comment by jeog** [comment]
There's an error in the setup script: it's not handling the space between 'Master' and 'Soe' properly. Because the path of the engine gets passed to the service I'll have to make some adjustments to the script when I get some time. 

In the meantime it should work if you move to a directory without a space.

**_Also, you shouldn't be passing 'Soe' to the script._** If your TOS runs under the admin account pass 'admin', if not passing nothing.

**Comment by shnog** [comment]
Ah gotcha. That makes sense. I always worried that some day the space in my user name would mess some things up. And I see, it is running under admin, I was just trying different users to see if it would change the error. Thanks for the help!

**Comment by jeog** [comment]
Glad it worked.  I don't do a lot of batch scripting so certainly some bad code in there. Surprised it took this long to break. 

Thanks for filing, you'll probably end of saving someone a headache.
