### ISSUE TITLE
Limit on number of items

### ISSUE THREAD

**Issue by caspersauce** [jeog/TOSDataBridge#26]
I getting errors like this:

library function [TOSDB_AddItem] returned error code [-29,ERROR_DECREMENT_BASE(-4)]

after accessing a significant number of items, for example:

1. create 10 blocks with 500 items each and 4 topics per item
2. wait for 100 data points in the block
3. get data
4. close 10 blocks

If I do the above steps 3 times, the system starts to fail and gives me the decrement or increment errors for almost every item added. They are definitely valid items, because if I restart  the entire computer I can then run the items. Just restarting the service does not fix the issue.

Obviously that is a ton of items, just curious if you have seen this behavior and if you there is a fix.

**Comment by jeog** [comment]
It's been a while since I saw that error, but it's generally used to indicate the number of errors occurring in a particular operation where there can be many of the same type(4 in that case). In this case you are getting multiple errors while trying to add all these items/topics to the engine. My best guess is that TOS or DDE is getting maxed out and failing for those new items/topics. 

When you close the blocks it should free the resources, and allow you to recreate. It's possible some are not getting removed properly. You can try using tos-databridge-shell-[].exe to examine the underlying resources. I think the 'Connect' command followed by 'DumpBufferStatus' will show what streams are active.

**Comment by caspersauce** [comment]
Finally had a chance to look at this. When I DumpBufferStatus, the log says:

 --- TOPIC INFO --- 
Topic                         Item                          Ref-Count 
 --- BUFFER INFO --- 
BufferName                                                  Handle          
 --- END END END --- 

I am assuming this means it considers itself empty. It is strange problem, I don't see any processes consuming a large amount of memory, and it requires a complete system restart to fix the issue.

**Comment by jeog** [comment]
My guess is 1) the number of items/topics added and/or large blocks continually opened/closed is causing a DDE error, and 2) that error is not being handled properly so some of the low level OS objects that manage the streams are not being cleaned up properly, until the system is restarted. 

Unfortunately, I don't have the time right now to debug that so I'd advise sticking to a more limited number of items/topics/blocks and avoiding repeatedly opening and closing blocks, if possible.
