### ISSUE TITLE
Issues with finding binaries 

### ISSUE THREAD

**Issue by rocketsman79** [jeog/TOSDataBridge#30]
hi, im fairly new to programming so please bare with me. im trying to run the tosdb-setup.bat file in cmd and i keep getting  "Can't find "C:\TOSBridge\\bin\\Release\\x64\\tos-databridge-serv-x64.exe", exiting setup...". ive checked that location to make sure the file is in there and it is so im not sure what's going on here. ive whitelisted the folder and have been following along with the instructions you've provided so any suggestions would be much appreciated.

**Comment by jeog** [comment]
Can you post a screenshot of the command you are using and all the output returned; and the contents of your bin\Release\x64 folder.

**Comment by rocketsman79** [comment]
![bin files](https://user-images.githubusercontent.com/76787876/103465272-f7a7a100-4d07-11eb-8aa9-3b7127ae92b1.PNG)
![ouput](https://user-images.githubusercontent.com/76787876/103465273-f7a7a100-4d07-11eb-90af-47ed35ce7cb3.PNG)

**Comment by jeog** [comment]
I think there may be an issue caused by the spaces in the 'python tests with auto gui' directory. The .bat script is probably not handling it correctly. Can you try replacing the spaces with another character e.g 'python_tests_with_auto_gui' or move TOSBridge to a different directory w/o spaces?

Simply surrounding the directory variables w/ quotes in the script (lines 60 and 64) may fix it but I'm not on a windows machine right now so can't test if will break something else.

**Comment by rocketsman79** [comment]
removing the spaces in the directory worked perfectly, thank you so much!
