### ISSUE TITLE
Is this able to run on MacOS/Linux? (Python client)

### ISSUE THREAD

**Issue by orshemtov** [jeog/TOSDataBridge#33]
Hi,

The README is a bit unclear about the requirements

Requirements
- Windows for the core implementation. (The python interface is available to any system running python3.)
- TDAmeritrade's ThinkOrSwim(TOS) platform that exposes DDE functionality (the Window's verion)
- VC++ 2012 Redistributable (included)

It states that the python version can run on any system but needs TOS windows version

Am I seeing something not right?

**Comment by jeog** [comment]
The python interface can communicate over TCP to a backend on a windows system. Since DDE only works on the WIndows version of TOS the backend is implemented as a WIndows Service - there is no way around that. So, if you can get windows running on a virtual machine, for instance, you can run the backend on that and connect over the local network.
